name: Daniel Gorelick | Creative Technologist in New York, NY

description: Professional portfolio for Daniel Gorelick – hardware and digital creative technologist working in the interactive new-media space.

footer-links:
  email: dqgorelick@gmail.com
  github: dqgorelick
  instagram: dqgorelick
  rss: dqgorelick
  twitter: dqgorelick

google_analytics: "UA-70796463-1"

url: "http://danielgorelick.com"

baseurl: ""

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded
  sass_dir: "assets/styles"

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - node_modules/
  - src/
  - projects/
  - server.js
  - webpack.config.js
  - webpack.production.config.js

markdown: kramdown
