$(document).ready(function(){
	$("#tech").mouseenter(function(){
		$("#backdropmain").fadeIn(0);
		$("#dropdown2").fadeOut(0);
		$("#dropdown3").fadeOut(0);
		$("#dropdown1").fadeIn(200);
		$("#backdrop2").fadeOut(0);
		$("#backdrop3").fadeOut(0);
		$("#backdrop1").fadeIn(0);
		$("#backdropmain").css("border-top-left-radius","0px");
		$("#backdropmain").css("border-top-right-radius","25px");
	}); 
	$("#music").mouseenter(function(){
		$("#backdropmain").fadeIn(0);
		$("#dropdown1").fadeOut(0);
		$("#dropdown3").fadeOut(0);
		$("#dropdown2").fadeIn(200);
		$("#backdrop1").fadeOut(0);
		$("#backdrop3").fadeOut(0);
		$("#backdrop2").fadeIn(0);
		$("#backdropmain").css("border-top-left-radius","25px");
		$("#backdropmain").css("border-top-right-radius","25px");
	});
	$("#design").mouseenter(function(){
		$("#backdropmain").fadeIn(0);
		$("#dropdown1").fadeOut(0);
		$("#dropdown2").fadeOut(0);
		$("#dropdown3").fadeIn(200);
		$("#backdrop1").fadeOut(0);
		$("#backdrop2").fadeOut(0);
		$("#backdrop3").fadeIn(0);
		$("#backdropmain").css("border-top-left-radius","25px");
		$("#backdropmain").css("border-top-right-radius","0px");
	});

	$("#toolbar").mouseenter(function(){
		$("#open").slideDown(100);
	});
	$("#toolbar").mouseleave(function(){
		$("#open").slideUp(100);
	});
});